apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudverse
  template:
    metadata:
      labels:
        app: cloudverse
    spec:
      containers:
      - name: cloudverse
        image:  nancykumari/cloudverse:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
